messages:
  console-disallowed: 'Команду невозможно выполнить от лица консоли.'
  player-missing: 'Указанного игрока нет на сервере.'
  no-args: 'Недостаточно аргументов команды.'
  reloaded: 'Успешно перезагружено.'
  player-exempted: 'Инвентарь этого игрока нельзя посмотреть.'
  too-far: 'Игрок слишком далеко от вас.'

item:
  type: SPYGLASS
  name: '&bЛупа'

distance: 2